[package]
name = "slbl-ui"
version = "0.1.0"
authors = ["Leo Letellier"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
iced = { version = "0.13.1", features = ["canvas"] }


[workspace]
members = ["src-logic"]

[workspace.dependencies]
src-logic = {path = "./src-logic"}
